package com.elvis.demo.mapper;

import com.elvis.demo.model.CoffeeOrder;
import com.elvis.demo.model.CoffeeOrderExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CoffeeOrderMapper {
	
	void insertCoffeeAndOrderMapping(CoffeeOrder record);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    long countByExample(CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    int deleteByExample(CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @Insert({
        "insert into coffee_order (update_time, create_time, ",
        "is_delete, customer, ",
        "status)",
        "values (#{updateTime,jdbcType=TIMESTAMP}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{isDelete,jdbcType=INTEGER}, #{customer,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(CoffeeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    int insertSelective(CoffeeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    List<CoffeeOrder> selectByExampleWithRowbounds(CoffeeOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    List<CoffeeOrder> selectByExample(CoffeeOrderExample example);

    List<CoffeeOrder> selectByCustomer(@Param("customer") String customer);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoffeeOrder record, @Param("example") CoffeeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    int updateByExample(@Param("record") CoffeeOrder record, @Param("example") CoffeeOrderExample example);
}