package com.elvis.demo.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.joda.money.Money;

import java.io.Serializable;
import java.util.Date;

public class Coffee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.name
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.price
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private Money price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.update_time
     *
     * @return the value of t_menu.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.update_time
     *
     * @param updateTime the value for t_menu.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.create_time
     *
     * @return the value of t_menu.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.create_time
     *
     * @param createTime the value for t_menu.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.is_delete
     *
     * @return the value of t_menu.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withIsDelete(Integer isDelete) {
        this.setIsDelete(isDelete);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.is_delete
     *
     * @param isDelete the value for t_menu.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.name
     *
     * @return the value of t_menu.name
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.name
     *
     * @param name the value for t_menu.name
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.price
     *
     * @return the value of t_menu.price
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Money getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Coffee withPrice(Money price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.price
     *
     * @param price the value for t_menu.price
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setPrice(Money price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append("]");
        return sb.toString();
    }
}