package com.elvis.demo.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CoffeeOrder implements Serializable {
	
	private List<Coffee> coffeelist;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.customer
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private String customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coffee_order.status
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private OrderState status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.id
     *
     * @return the value of coffee_order.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.id
     *
     * @param id the value for coffee_order.id
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.update_time
     *
     * @return the value of coffee_order.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.update_time
     *
     * @param updateTime the value for coffee_order.update_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.create_time
     *
     * @return the value of coffee_order.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.create_time
     *
     * @param createTime the value for coffee_order.create_time
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.is_delete
     *
     * @return the value of coffee_order.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withIsDelete(Integer isDelete) {
        this.setIsDelete(isDelete);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.is_delete
     *
     * @param isDelete the value for coffee_order.is_delete
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.customer
     *
     * @return the value of coffee_order.customer
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withCustomer(String customer) {
        this.setCustomer(customer);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.customer
     *
     * @param customer the value for coffee_order.customer
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coffee_order.status
     *
     * @return the value of coffee_order.status
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public OrderState getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public CoffeeOrder withStatus(OrderState status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coffee_order.status
     *
     * @param status the value for coffee_order.status
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    public void setStatus(OrderState status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coffee_order
     *
     * @mbg.generated Wed Mar 06 16:51:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", customer=").append(customer);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }

    public List<Coffee> getCoffeelist() {
        return coffeelist;
    }

    public void setCoffeelist(List<Coffee> coffeelist) {
        this.coffeelist = coffeelist;
    }
}